### ISSUE TITLE
access git over ssh rather than http

### ISSUE THREAD

**Issue by sallyom** [containers/fetchit#244]
we want to allow accessing git by ssh, with a provided (private) ssh key mounted to fetchit pod - probably will want this to be the default once we prove it's working - this will also include updating all the workflows to use ssh

**Comment by sallyom** [comment]
as per @josephsawaya 's slack comment, something like this to the fetchit config
```
git-auth:
  ssh:
  username: (not recommended)
  password: (not recommended)
  pat:
```
