### ISSUE TITLE
[RFC]/[feature request] Allow multiple urls for the same repository?

### ISSUE THREAD

**Issue by guest20** [containers/fetchit#284]
As a dev with trust issues I want to be able to specify multiple urls for the same git repo, so that I can still update my config when github is down.

for example, one can ask gitlab to maintain a mirror of a git repo hosted elsewhere, so something like:

```yaml
targetConfigs:
- url: 
    - http://github.com/example/fetchit-config
    - http://gitlab.com/example_mirror/fetchit-config
```

... would allow me to push patches/PRs at the github version under normal circumstances, and (as long as gitlab keeps my mirror up to date) my host(s) can just use the gitlab mirror if github forget to pay their aws bills, some jerk ddos's them, or I delete my account on accident... 

This might also be good if one's host(s) each maintain a regularly updating `git clone --bare` that can be referred to with a `file://` url
