### ISSUE TITLE
Kustomize, Helm, sops or any other tool to change input before fetchit method run

### ISSUE THREAD

**Issue by ancosma** [containers/fetchit#308]
I'm using fetchit with kube method and the input is generated by running kustomize and sops.
The main problem is that the output contains decrypted secrets so storing in repo in not safe - it has to run on the server before the content is feed to podman kube. Seems that's not possible to do in fetchit currently.
Would be nice to have some mechanism like [config-management-plugins](https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/) like in ArgoCD to be able to run for example `kustomize build` and take the output and feed it into the method (in my case kube).
Would you accept a PR for such a feature (kinda pre-processor of the input)? If yes, maybe we can discuss about the possible config before I proceed with the implementation. Something like
```yaml
pre-sync: ["kustomize", "build"]
# or
pre-sync: "kustomize build"
# or
generate: ["kustomize", "build"]
```
to be added to each method?
